//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 12:45:50 PM CST 
//

package trng.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;

import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for customer complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="customer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cutomerId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="paymentMethod" type="{http://www.example.org/paymentMethod}paymentMethod"/>
 *         &lt;element name="annualSalary" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="address" type="{http://www.example.org/address}address"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customer", namespace = "http://www.example.org/Customer", propOrder = { "cutomerId", "name",
		"dateOfBirth", "paymentMethod", "annualSalary", "address" })
@XmlRootElement
public class Customer {

	protected int cutomerId;
	@XmlElement(required = true)
	protected String name;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar dateOfBirth;
	@XmlElement(required = true)
	protected PaymentMethod paymentMethod;
	protected float annualSalary;
	@XmlElement(required = true)
	protected Address address;

	/**
	 * Gets the value of the cutomerId property.
	 * 
	 */
	public int getCutomerId() {
		return cutomerId;
	}

	/**
	 * Sets the value of the cutomerId property.
	 * 
	 */
	public void setCutomerId(int value) {
		this.cutomerId = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the dateOfBirth property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDateOfBirth() {
		return dateOfBirth;
	}

	/**
	 * Sets the value of the dateOfBirth property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDateOfBirth(XMLGregorianCalendar value) {
		this.dateOfBirth = value;
	}

	/**
	 * Gets the value of the paymentMethod property.
	 * 
	 * @return possible object is {@link PaymentMethod }
	 * 
	 */
	public PaymentMethod getPaymentMethod() {
		return paymentMethod;
	}

	/**
	 * Sets the value of the paymentMethod property.
	 * 
	 * @param value
	 *            allowed object is {@link PaymentMethod }
	 * 
	 */
	public void setPaymentMethod(PaymentMethod value) {
		this.paymentMethod = value;
	}

	/**
	 * Gets the value of the annualSalary property.
	 * 
	 */
	public float getAnnualSalary() {
		return annualSalary;
	}

	/**
	 * Sets the value of the annualSalary property.
	 * 
	 */
	public void setAnnualSalary(float value) {
		this.annualSalary = value;
	}

	/**
	 * Gets the value of the address property.
	 * 
	 * @return possible object is {@link Address }
	 * 
	 */
	public Address getAddress() {
		return address;
	}

	/**
	 * Sets the value of the address property.
	 * 
	 * @param value
	 *            allowed object is {@link Address }
	 * 
	 */
	public void setAddress(Address value) {
		this.address = value;
	}

}
